Adding plugins needed for release
javaee/logging-annotation-processor pull request #2
Opened 2018-03-26 09:05 UTC by kokil12

2018-03-26 16:50 UTC, yaminikb requested changes

2018-03-26 16:50 UTC, yaminikb commented on pom.xml
> +				<![CDATA[Copyright &#169; 1996-2013,
Update the year

2018-03-27 06:12 UTC, kokil12 commented on pom.xml
> +				<![CDATA[Copyright &#169; 1996-2013,
Updated the copyright year.

2018-03-27 07:20 UTC, yaminikb approved these changes

2018-03-27 07:20 UTC, merged